name: 'LocalGov Drupal'
description: 'Installs and configures LocalGov Drupal and supporting modules.'
type: 'Site'

install:
  # Install core dependencies.
  - config
  - help
  # Install Claro as it is a dependency of Gin, but don't import config.
  - claro
  # Install Toolbar as it is a dependency of Gin Toolbar.
  - toolbar
  - admin_toolbar
  - admin_toolbar_tools
  # Install Gin theme and base modules that extend it.
  - gin
  - gin_login
  - gin_toolbar
  # Contrib
  - entity_browser
  - paragraphs
  - preview_link
  - simple_sitemap
  - redirect
  # LocalGov Drupal
  - localgov_base
  - localgov_scarfolk
  - localgov_admin_theme_improvements
  - localgov_core
  - localgov_login_redirect
  - localgov_media
  - localgov_menu_link_group
  - localgov_page_components
  - localgov_paragraphs
  - localgov_roles
  - localgov_services
  - localgov_services_landing
  - localgov_services_navigation
  - localgov_services_page
  - localgov_services_sublanding

config:
  import:
    admin_toolbar: '*'
    admin_toolbar_tools: '*'
    entity_browser: '*'
    paragraphs: '*'
    preview_link: '*'
    simple_sitemap: '*'
    redirect: '*'
    gin:
      - gin.settings
      - block.block.gin_breadcrumbs
      - block.block.gin_content
      - block.block.gin_help
      - block.block.gin_local_actions
      - block.block.gin_messages
      - block.block.gin_page_title
      - block.block.gin_primary_local_tasks
    gin_login: '*'
    localgov_base: '*'
    localgov_scarfolk: '*'
    localgov_admin_theme_improvements: '*'
    localgov_core: '*'
    # localgov_login_redirect: '*' is part of install profile
    localgov_media: '*'
    localgov_menu_link_group: '*'
    # localgov_page_components: '*'
    # localgov_paragraphs: '*'
    localgov_roles: '*'
    localgov_topics: '*'
    # localgov_services: '*'
    # localgov_services_landing: '*'
    # localgov_services_navigation: '*'
    # localgov_services_page: '*'
    # localgov_services_sublanding: '*'
  actions:
    # Set and unset Gin blocks.
    block.block.gin_admin:
      simple_config_update:
        status: false
    block.block.gin_branding:
      simple_config_update:
        status: false
    block.block.gin_local_actions:
      simple_config_update:
        region: content
        weight: -10
    block.block.gin_local_tasks:
      simple_config_update:
        status: false
    block.block.gin_page_title:
      simple_config_update:
        region: header
        weight: -10
    block.block.gin_primary_local_tasks:
      simple_config_update:
        region: header
        weight: -5
        settings.secondary: true
    block.block.gin_tools:
      simple_config_update:
        status: false
    # Update core date settings
    core.date_format.long:
      simple_config_update:
        pattern: 'l j F Y \a\t g:ia'
    core.date_format.medium:
      simple_config_update:
        pattern: 'D d/m/Y g:ia'
    core.date_format.short:
      simple_config_update:
        pattern: 'd/m/Y g:ia'
    # Update the admin theme to Gin in Theme settings.
    gin.settings:
      simple_config_update:
        classic_toolbar: horizontal
    node.settings:
      simple_config_update:
        use_admin_theme: true
    system.theme:
      simple_config_update:
        admin: gin
        default: localgov_scarfolk
