name: 'LocalGov Drupal'
description: 'Installs and configures LocalGov Drupal and supporting modules.'
type: 'Site'

recipes:
  - localgov_drupal_admin_theme
install:
  # Core
  - ckeditor5
  - config
  - editor
  - filter
  - media
  - media_library
  - views
  # Contrib
  - entity_browser
  - linkit
  - paragraphs
  - paragraphs_library
  - preview_link
  - simple_sitemap
  - redirect
  # LocalGov Drupal
  - localgov_base
  - localgov_scarfolk
  - localgov_admin_theme_improvements
  - localgov_core
  # - localgov_login_redirect // part of install profile
  - localgov_media
  - localgov_menu_link_group
  - localgov_page_components
  - localgov_paragraphs
  - localgov_roles
  - localgov_topics
  # - localgov_services
  # - localgov_services_landing
  # - localgov_services_navigation
  # - localgov_services_page
  # - localgov_services_sublanding

config:
  import:
    # Core
    ckeditor5: '*'
    editor: '*'
    media: '*'
    media_library: '*'
    # Contrib
    admin_toolbar: '*'
    admin_toolbar_tools: '*'
    entity_browser: '*'
    linkit: '*'
    paragraphs: '*'
    paragraphs_library: '*'
    preview_link: '*'
    simple_sitemap: '*'
    redirect: '*'
    # LocalGov Drupal
    localgov_base: '*'
    localgov_scarfolk: '*'
    localgov_admin_theme_improvements: '*'
    localgov_core: '*'
    # localgov_login_redirect: '*'
    localgov_media: '*'
    localgov_menu_link_group: '*'
    localgov_page_components: '*'
    localgov_paragraphs: '*'
    localgov_roles: '*'
    localgov_topics: '*'
    # localgov_services: '*'
    # localgov_services_landing: '*'
    # localgov_services_navigation: '*'
    # localgov_services_page: '*'
    # localgov_services_sublanding: '*'
  actions:
    # Update core date settings
    core.date_format.long:
      simple_config_update:
        pattern: 'l j F Y \a\t g:ia'
    core.date_format.medium:
      simple_config_update:
        pattern: 'D d/m/Y g:ia'
    core.date_format.short:
      simple_config_update:
        pattern: 'd/m/Y g:ia'
    node.settings:
      simple_config_update:
        use_admin_theme: true
    system.theme:
      simple_config_update:
        default: localgov_scarfolk
