name: Admin Theme
type: LocalGov Drupal
description: Sets up a nice administrative theme and navigation.

install:
  - gin
  - gin_toolbar
  - help
config:
  import:
    gin: '*'
  actions:
    system.theme:
      simple_config_update:
        admin: gin
        classic_toolbar: horizontal
